base_url = "https://whispers-on-parchment.jasonfry.co.uk"

build_search_index = false
title = "Whispers on Parchment"
description = ""
generate_feeds = true
feed_filenames = ["rss.xml"]

head_title = "Whispers on Parchment, by Edward Fitzgerald"
 [[extra.footer_menu]]
    [[extra.footer_menu.links]]
      text = "Made With Zola"
      href = "https://getzola.org"
    [[extra.footer_menu.links]]
      text = "Parchment theme, by Jason Fry"
      href = "https://jasonfry.co.uk"
